server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: https://auth-service-efev.onrender.com
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: https://user-service-yomu.onrender.com
          predicates:
            - Path=/api/user/**
          filters:
            - JwtValidationFilter

        - id: billing-service
          uri: https://bill-service-6fnu.onrender.com
          predicates:
            - Path=/api/bill/**
          filters:
            - JwtValidationFilter

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG